#!/bin/bash
# 2/04/2016 AGorzawski: 
if [ "$1" == "-h" ]; then
	echo " "
	echo "This script simplfies the calculations with the TRAIN code."
	echo "It creates a setup.input file for given filling pattern file."
	echo "The results for a simple calculation are stored under the folder (inside RESULTS) with the filling file name."
	echo "For more more customized simulation run 'runTrainWithInputFile.sh' script"
	echo " "
	echo "    usage:  runTrainForFillingScheme.sh {fillingSchemeFile} {plot|noplot}"
	echo " "
  exit 0
fi

if [ "$#" -ne 2 ]; then
    echo " "
    echo "Illegal number of parameters - NO FILLING SCHEME defined!"
    echo "    try:  runTrainWithInputName.sh -h"
    echo " "
    exit 0
fi
#keep this name unchenged - moveResultsToSubFolder.sh uses the same subfolder
mkdir -p RESULTS
fillingSchemeFile=`basename $1`


# the part for parsing the setup.temp file
bunches_B1=$(grep -Ec '^[0-9]+ 1' "$fillingSchemeFile")
bunches_B2=$(grep -Ec '^[0-9]+ [01] 1' "$fillingSchemeFile")
echo "Number of Bunches: $bunches_B1 / $bunches_B2 (will use B1 for tune)"
NUMBER_OF_BUNCHES=$bunches_B1
echo 'GENERATING the setup.input file for '$fillingSchemeFile
templatefile=setup.temp
outputfile=setup.input
FILLING_SCHEME=FillingSchemes/$fillingSchemeFile
COMMENT='THIS FILE IS AUTOMATICALLY GENERATED AND READY TO BE USED AS TRAIN INPUT'
echo "$(eval "echo \"$(cat $templatefile)\"")" > $outputfile

echo '... input file Generated.'

./runTrainWithInputFile.sh $fillingSchemeFile $2
